#!/bin/bash

set -x

set -eo pipefail

# Check whether the database is actually ready.

if [ "$KALLITHEA_DATABASE_TYPE" = "postgresql" ]; then
    python $WARPDRIVE_SRC_ROOT/.warpdrive/util_scripts/check-postgresql.py
fi

# Runs the database migration.
#
# This script should be executed using the 'warpdrive migrate' command
# from a 'mid' hook. The deployment should only ever use a 'Recreate'
# strategy and not a 'Rolling' strategy to ensure that database
# migrations are done when no processes are trying to access the
# database.

paster upgrade-db $WARPDRIVE_APP_ROOT/tmp/production.ini --force-yes
