#!/bin/bash

set -x

mkdir -p $WARPDRIVE_APP_ROOT/data/repos

paster setup-db \
    $WARPDRIVE_APP_ROOT/tmp/production.ini \
    --user="$KALLITHEA_ADMIN_USERNAME" \
    --password="$KALLITHEA_ADMIN_PASSWORD" \
    --email="$KALLITHEA_ADMIN_EMAIL" \
    --repos="$WARPDRIVE_APP_ROOT/data/repos" \
    --force-yes
